### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by AhmedAbo6** [rafaelurben/django-discordbot#121]
I can't find any docs
there for I am stuck at the beginning of the configurations of the TOKEN

**Comment by rafaelurben** [comment]
Thank you for your issue! Because this project was never really meant to be used by other people and was more or less an experiment, I never wrote a documentation for it. But now it looks like people are getting interested in this, so I'll add some documentation in the future and maybe I'll even add an English translation for the bot itself (it's only German atm).

I'll try to make a simple documentation in a few hours. I'll keep you up to date ;)

**Comment by rafaelurben** [comment]
I only had time to update the [setup instructions](https://github.com/rafaelurben/django-discordbot/blob/master/docs/setup.md) at the moment, but they should help with your issue. 😉

Hope this helps ;)
